apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app-deployment
  namespace: py-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
        - name: py-app
          image: registry.k8s.foo:32699/py-app
          ports:
            - containerPort: 8000
        - name: redis
          image: redis:alpine
      imagePullSecrets:
        - name: registry-auth
