apiVersion: v1
kind: Service
metadata:
  name: py-app-service
  namespace: py-app
spec:
  selector:
    app: py-app
  ports:
    - name: py-app
      port: 8000
      targetPort: 8000
  type: NodePort
