Vagrant.configure(2) do |config|

  (1..3).each do |i|
    config.vm.define "k8s-#{i}" do |s|
      s.ssh.forward_agent = true
      s.vm.box = "ubuntu/focal64"
      s.vm.hostname = "k8s-#{i}"
      s.vm.network "private_network", ip: "172.16.8.10#{i}", netmask: "255.255.255.0", auto_config: true, virtualbox__intnet: "k8s-net"
      s.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: [
        "wlp0s20f3", # Dell XPS 15 9510,
        "enp0s31f6", # Home LAN
        "wlp3s0"     # Home Wifi
      ]
      s.vm.provider "virtualbox" do |v|
        v.name = "k8s-#{i}"
        v.cpus = 2
        v.memory = 3072
        v.gui = false
      end

      if i == 1
        s.vm.provision :shell do |c|
          c.inline = "bash /vagrant/scripts/bootstrap_registry.sh $1"
          c.args = ["172.16.8.101"]
        end
      elsif i == 2
        s.vm.provision :shell do |c|
          c.inline = "bash /vagrant/scripts/bootstrap_master.sh $1 $2"
          c.args = ["172.16.8.101", "172.16.8.102"]
        end
      else
        s.vm.provision :shell do |c|
          c.inline = "bash /vagrant/scripts/bootstrap_worker.sh $1 $2 $3"
          c.args = ["172.16.8.101", "172.16.8.102", "172.16.8.10#{i}"]
        end
      end
    end
  end

end