# 
# you will need: 
# vagrant plugin install vagrant-env
# to run this piece of s**t
#

Vagrant.configure(2) do |config|
  config.env.enable # Enable vagrant-env(.env)
  # puts "am gasit ip #{vm_ip}"

  (1..2).each do |i|
    config.vm.define "k8s-#{i}" do |s|
      s.ssh.forward_agent = true
      s.vm.box = "ubuntu/focal64"

      vm_ip = ENV['HOST_IP_RANGE']
      
      s.vm.hostname = "k8s-#{i}"
      
      s.vm.network "private_network", ip: vm_ip.sub("*", (100 + i).to_s), netmask: "255.255.255.0", auto_config: true, virtualbox__intnet: "k8s-net"
      
      s.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: [
        "wlp0s20f3", # Dell XPS 15 9510,
        "enp0s31f6", # Home LAN
        "wlp3s0"     # Home Wifi
      ]
      
      s.vm.provider "virtualbox" do |v|
        v.name = "k8s-#{i}"
        v.cpus = 2
        v.memory = 3072
        v.gui = false
      end

      if i == 1
        s.vm.provision :shell do |c|
          c.inline = "bash /vagrant/scripts/bootstrap.sh --master --advertise-address $1"
          c.args = [vm_ip.sub("*", "101")]
        end
      else
        s.vm.provision :shell do |c|
          c.inline = "bash /vagrant/scripts/bootstrap.sh --worker --advertise-address $1"
          c.args = [vm_ip.sub("*", "101")]
        end
      end
    end
  end

end