Vagrant.configure(2) do |config|

  config.vm.define "minikube" do |s|
    s.ssh.forward_agent = true
    s.vm.box = "ubuntu/jammy64"
    s.vm.hostname = "minikube"
    s.vm.network "private_network", ip: "192.168.56.101", netmask: "255.255.255.0", auto_config: true, virtualbox__intnet: "minikube-net"
    s.vm.network "public_network", use_dhcp_assigned_default_route: true
    s.vm.provider "virtualbox" do |v|
      v.name = "minikube"
      v.cpus = 2
      v.memory = 4096
      v.gui = false
    end

    # s.vm.provision :shell, path: "scripts/bootstrap_master.sh", args: ["192.168.56.101"]
    s.vm.provision :shell do |c|
      c.inline = "bash /opt/swarm/bootstrap.sh"
    end

    s.vm.synced_folder "scripts/", "/opt/swarm"
  end

end