apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: image-pull-secret
data:
  # .dockerconfigjson: {{ "{\"auths\": {\"172.16.8.101:5000\": {\"username\": \"testuser\", \"testpassword\": \"a1b2c3d4e5f6\"}}}" | b64enc }}
  .dockerconfigjson: eyJhdXRocyI6IHsiMTcyLjE2LjguMTAxOjUwMDAiOiB7InVzZXJuYW1lIjogInRlc3R1c2VyIiwgInRlc3RwYXNzd29yZCI6ICJhMWIyYzNkNGU1ZjYifX19Cg==
