apiVersion: v1
kind: Pod
metadata:
  name: py-app
spec:
  containers:
    - name: py-app
      image: registry.k8s.foo:5000/py-app
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
  imagePullSecrets:
    - name: private-registry-credentials
